[package]
name = "rusty-days-hack"
version = "0.1.0"
authors = ["Zoran Lazarevic <lazarevic.zoki91@gmail.com>"]
edition = "2018"

[dependencies]
image = { version = "0.23.8", features = ["png"] }
rayon = "1.3.1"
